### ISSUE TITLE
Input Type vs Component Type

### ISSUE THREAD

**Issue by ericf89** [HurricaneJames/lazy-input#2]
I wanted to let you know the v1.1.0 release introduce a breaking change to our project.   We currently pass several different `type`s to our lazy inputs like `number`, `tel`, and `email` so that mobile browsers display the correct keyboard to our users.    But we still want literal html input nodes to be rendered. :) 

Perhaps we could change add a special `input_type` prop that would be translated to `type` on the resulting node?   Or, even better might be to change the name of lazy input's `type` to `component` or something similar since `type` is already used by the browser.  

I'll try to submit a PR sometime this weekend if I have a chance, but we've frozen our project at 1.0.10 for  now. 

Thanks for all the hard work!

**Comment by HurricaneJames** [comment]
Oh, good point. I have a couple projects doing the same thing. Unfortunately, they are still using Lazy-Input v1.0 or I would have seen this issue sooner. I think adding a `componentType` prop will work. Then we can go back to the original method of using "textarea" for textarea and "input" for everything else unless we override with `componentType`.

**Comment by HurricaneJames** [comment]
I think I found a better solution. If the type is a function, use it. If it is a string, go back to the original behavior. Everybody is happy, no prop creep.

```
  render: function() {
    var componentType = (typeof this.props.type === 'function') ? this.props.type : (this.props.type === "textarea" ? "textarea" : "input");
    return React.createElement(componentType, this.getProps());
  }
```

**Comment by ericf89** [comment]
Ooooo. Very nice.  I like that. :+1:

**Comment by HurricaneJames** [comment]
Thanks for closing this, guess I forgot.

**Comment by ericf89** [comment]
All good.  1.1.1 works for us! Thanks for the quick turn around.

**Comment by HurricaneJames** [comment]
Thanks for the suggestion. Glad to know people are using this.
